# Generated by Django 2.1 on 2020-04-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200402_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='where',
            field=models.ManyToManyField(related_name='plants', related_query_name='plant', to='plants.SpecificArea'),
        ),
    ]
